apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kube-hello-world-ingress
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: kube-hello-world-service
          servicePort: 80
        path: /

